### ISSUE TITLE
Test suite QuickCheck failure

### ISSUE THREAD

**Issue by snoyberg** [haskell-crypto/cryptonite#28]
```
    generate-param-odd:      FAIL
      *** Failed! Falsifiable (after 56 tests):
      TestDRG (14634184162,172342014,14634914744,16093274693,6665281464)
      Int0_2901 0
      Use --quickcheck-replay '55 TFGenR 000000005F255FBD000000000007A120000000000000DFA500000001B378B680 0 1152921504606846960 60 0' to reproduce.
```

Occurred with version 0.6.

**Comment by vincenthz** [comment]
has been fixed in the repository for a while. need to release a new version though.

**Comment by nomeata** [comment]
Ah, sorry for not searching first. Is there a single particular commit that I could apply to the Debian package?

**Comment by vincenthz** [comment]
@nomeata it's 169570c9632a29c95432468016f294853bcd1ba2

**Comment by nomeata** [comment]
Thanks! Applied it to the Debian package, together with the other patches I suggested today. Let’s see how well that goes.

**Comment by nomeata** [comment]
Looks like I still get this:

```
    generate-param:          FAIL
      *** Failed! Falsifiable (after 82 tests): 
      TestDRG (437993943873007,1050657333325426,1824512674053348,1546774482379053,23414001285279)
      Int0_2901 0
      Use --quickcheck-replay '81 TFGenR 7D1E6987D152076F136A688E2627DEF80114C16CF0ADB8AE20DF36049CF5B9E5 0 1048575 20 0' to reproduce.
```

Maybe the `generate-param` tests (and the others) need a similar guard as in 169570c, or alternatively, a different newtype could be used (`Int1_2901`?)

**Comment by vincenthz** [comment]
has been fixed in cryptonite 0.7
